[workspace]
members = [
    "ricq",
    "ricq-core",
    "ricq-guild"
]

[profile.dev]
debug = false # this switch disabled backtrace
panic = "abort"
[profile.dev.package."*"]
debug = false
strip = true
opt-level = "z"
