[package]
name = "ricq"
version = "0.1.16"
edition = "2021"
description = "Android IM protocol"
license = "AGPL-3.0"
homepage = "https://github.com/lz1998/ricq"
repository = "https://github.com/lz1998/ricq"
readme = "README.md"
keywords = ["qq", "protocol", "android", "mirai"]

[features]
default = []
image-detail = ["image"]

[dependencies]
ricq-core = { version = "0.1.16", path = "../ricq-core" }
async-trait = "0.1"
bytes = "1"
cached = { version = "0.30", features = ["async"], default-features = false }
derivative = "2"
flate2 = { version = "1", features = ["rust_backend"], default-features = false }
futures-util = "0.3"
image = { version = "0.24", optional = true }
jcers = "0.1"
md5 = "0.7"
prost = { version = "0.9", features = ["std"], default-features = false }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
tracing = "0.1"
